/*
-- Date: 2014-04-10 11:03
*/
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (2,'Abkhazian','Аҧсуа',0,'ab','abk');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (3,'Afar','Afaraf',0,'aa','aar');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (4,'Afrikaans','Afrikaans',0,'af','afr');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (5,'Akan','Akan',0,'ak','aka');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (6,'Albanian','Shqip',0,'sq','sqi');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (7,'Amharic','አማርኛ',0,'am','amh');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (8,'Arabic','العربية',0,'ar','ara');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (9,'Aragonese','Aragonés',0,'an','arg');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (10,'Assamese','অসমীয়া',0,'as','asm');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (11,'Armenian','Հայերեն',0,'hy','hye');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (12,'Avaric','авар мацӀ, магӀарул мацӀ',0,'av','ava');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (13,'Avestan','avesta',0,'ae','ave');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (14,'Aymara','aymar aru',0,'ay','aym');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (15,'Azerbaijani','azərbaycan dili',0,'az','aze');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (16,'Bashkir','башҡорт теле',0,'ba','bak');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (17,'Bambara','bamanankan',0,'bm','bam');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (18,'Basque','euskara, euskera',0,'eu','eus');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (19,'Belarusian','Беларуская',0,'be','bel');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (20,'Bengali','বাংলা',0,'bn','ben');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (21,'Bihari','भोजपुरी',0,'bh','bih');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (22,'Bislama','Bislama',0,'bi','bis');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (23,'Bosnian','bosanski jezik',0,'bs','bos');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (24,'Breton','brezhoneg',0,'br','bre');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (25,'Bulgarian','български език',0,'bg','bul');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (26,'Burmese','ဗမာစာ',0,'my','mya');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (27,'Catalan; Valencian','Català',0,'ca','cat');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (28,'Chamorro','Chamoru',0,'ch','cha');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (29,'Chechen','нохчийн мотт',0,'ce','che');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (30,'Chichewa; Chewa; Nyanja','chiCheŵa, chinyanja',0,'ny','nya');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (31,'Chinese','中文 (Zhōngwén), 汉语, 漢語',0,'zh','zho');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (32,'Chuvash','чӑваш чӗлхи',0,'cv','chv');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (33,'Cornish','Kernewek',0,'kw','cor');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (34,'Corsican','corsu, lingua corsa',0,'co','cos');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (35,'Cree','ᓀᐦᐃᔭᐍᐏᐣ',0,'cr','cre');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (36,'Croatian','hrvatski',0,'hr','hrv');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (37,'Czech','česky, čeština',0,'cs','ces');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (38,'Danish','dansk',0,'da','dan');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (39,'Divehi; Dhivehi; Maldivian;','ދިވެހި',0,'dv','div');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (40,'Dzongkha','རྫོང་ཁ',0,'dz','dzo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (41,'English','English',0,'en','eng');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (42,'Esperanto','Esperanto',0,'eo','epo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (43,'Estonian','eesti, eesti keel',0,'et','est');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (44,'Ewe','Eʋegbe',0,'ee','ewe');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (45,'Faroese','føroyskt',0,'fo','fao');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (46,'Fijian','vosa Vakaviti',0,'fj','fij');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (47,'Finnish','suomi, suomen kieli',0,'fi','fin');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (48,'French','français, langue française',0,'fr','fra');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (49,'Fula; Fulah; Pulaar; Pular','Fulfulde, Pulaar, Pular',0,'ff','ful');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (50,'Galician','Galego',0,'gl','glg');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (51,'German','Deutsch',0,'de','deu');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (52,'Greek, Modern','Ελληνικά',0,'el','ell');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (53,'Guaraní','Avañe\'ẽ',0,'gn','grn');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (54,'Gujarati','ગુજરાતી',0,'gu','guj');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (55,'Haitian; Haitian Creole','Kreyòl ayisyen',0,'ht','hat');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (56,'Hausa','Hausa, هَوُسَ',0,'ha','hau');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (57,'Hebrew, Modern','עברית',0,'he','heb');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (58,'Herero','Otjiherero',0,'hz','her');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (59,'Hindi','हिन्दी, हिंदी',0,'hi','hin');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (60,'Hiri Motu','Hiri Motu',0,'ho','hmo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (61,'Hungarian','Magyar',0,'hu','hun');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (62,'Interlingua (International Auxiliary Language Association)','Interlingua',0,'ia','ina');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (63,'Indonesian','Bahasa Indonesia',0,'id','ind');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (64,'Interlingue, Occidental','Interlingue',0,'ie','ile');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (65,'Irish','Gaeilge',0,'ga','gle');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (66,'Igbo','Igbo',0,'ig','ibo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (67,'Sichuan Yi, Nuosu','ꆇꉙ',0,'ii','iii');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (68,'Inupiaq','Iñupiaq, Iñupiatun',0,'ik','ipk');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (69,'Ido','Ido',0,'io','ido');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (70,'Icelandic','Íslenska',0,'is','isl');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (71,'Italian','Italiano',0,'it','ita');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (72,'Inuktitut','ᐃᓄᒃᑎᑐᑦ',0,'iu','iku');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (73,'Japanese','日本語 (にほんご／にっぽんご)',0,'ja','jpn');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (74,'Javanese','basa Jawa',0,'jv','jav');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (75,'Georgian','ქართული',0,'ka','kat');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (76,'Kongo','KiKongo',0,'kg','kon');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (77,'Kikuyu, Gikuyu','Gĩkũyũ',0,'ki','kik');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (78,'Kwanyama, Kuanyama','Kuanyama',0,'kj','kua');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (79,'Kazakh','Қазақ тілі',0,'kk','kaz');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (80,'Kalaallisut, Greenlandic','kalaallisut, kalaallit oqaasii',0,'kl','kal');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (81,'Central Khmer','ភាសាខ្មែរ',0,'km','khm');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (82,'Kannada','ಕನ್ನಡ',0,'kn','kan');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (83,'Korean','한국어 (韓國語), 조선말 (朝鮮語)',0,'ko','kor');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (84,'Kanuri','Kanuri',0,'kr','kau');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (85,'Kashmiri','कश्मीरी, كشميري‎',0,'ks','kas');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (86,'Kurdish','Kurdî, كوردی‎',0,'ku','kur');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (87,'Komi','коми кыв',0,'kv','kom');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (88,'Kirghiz, Kyrgyz','кыргыз тили',0,'ky','kir');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (89,'Latin','latine, lingua latina',0,'la','lat');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (90,'Luxembourgish, Letzeburgesch','Lëtzebuergesch',0,'lb','ltz');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (91,'Luganda','Luganda',0,'lg','lug');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (92,'Limburgish, Limburgan, Limburger','Limburgs',0,'li','lim');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (93,'Lingala','Lingála',0,'ln','lin');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (94,'Lao','ພາສາລາວ',0,'lo','lao');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (95,'Lithuanian','lietuvių kalba',0,'lt','lit');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (96,'Luba-Katanga','',0,'lu','lub');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (97,'Latvian','latviešu valoda',0,'lv','lav');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (98,'Malagasy','Malagasy fiteny',0,'mg','mlg');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (99,'Marshallese','Kajin M̧ajeļ',0,'mh','mah');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (100,'Manx','Gaelg, Gailck',0,'gv','glv');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (101,'Māori','te reo Māori',0,'mi','mri');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (102,'Macedonian','македонски јазик',0,'mk','mkd');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (103,'Malayalam','മലയാളം',0,'ml','mal');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (104,'Mongolian','Монгол',0,'mn','mon');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (105,'Marathi','मराठी',0,'mr','mar');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (106,'Malay','bahasa Melayu, بهاس ملايو‎',0,'ms','msa');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (107,'Maltese','Malti',0,'mt','mlt');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (108,'Nauru','Ekakairũ Naoero',0,'na','nau');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (109,'Norwegian Bokmål','Norsk bokmål',0,'nb','nob');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (110,'North Ndebele','isiNdebele',0,'nd','nde');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (111,'Nepali','नेपाली',0,'ne','nep');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (112,'Ndonga','Owambo',0,'ng','ndo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (113,'Dutch, Flemish','Nederlands, Vlaams',0,'nl','nld');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (114,'Norwegian Nynorsk','Norsk nynorsk',0,'nn','nno');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (115,'Norwegian','Norsk',0,'no','nor');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (116,'South Ndebele','isiNdebele',0,'nr','nbl');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (117,'Navajo, Navaho','Diné bizaad, Dinékʼehǰí',0,'nv','nav');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (118,'Occitan (after 1500)','Occitan',0,'oc','oci');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (119,'Ojibwa','ᐊᓂᔑᓈᐯᒧᐎᓐ',0,'oj','oji');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (120,'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic','ѩзыкъ словѣньскъ',0,'cu','chu');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (121,'Oromo','Afaan Oromoo',0,'om','orm');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (122,'Oriya','ଓଡ଼ିଆ',0,'or','ori');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (123,'Ossetian, Ossetic','Ирон æвзаг',0,'os','oss');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (124,'Panjabi, Punjabi','ਪੰਜਾਬੀ, پنجابی‎',0,'pa','pan');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (125,'Pāli','पाऴि',0,'pi','pli');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (126,'Persian','فارسی',0,'fa','fas');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (127,'Polish','polski',0,'pl','pol');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (128,'Pashto, Pushto','پښتو',0,'ps','pus');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (129,'Portuguese','Português',0,'pt','por');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (130,'Quechua','Runa Simi, Kichwa',0,'qu','que');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (131,'Romansh','rumantsch grischun',0,'rm','roh');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (132,'Kirundi','kiRundi',0,'rn','run');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (133,'Romanian, Moldavian, Moldovan','română',0,'ro','ron');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (134,'Russian','Русский язык',0,'ru','rus');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (135,'Kinyarwanda','Ikinyarwanda',0,'rw','kin');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (136,'Sanskrit','संस्कृतम्',0,'sa','san');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (137,'Sardinian','sardu',0,'sc','srd');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (138,'Sindhi','सिन्धी, سنڌي، سندھی‎',0,'sd','snd');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (139,'Northern Sami','Davvisámegiella',0,'se','sme');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (140,'Samoan','gagana fa\'a Samoa',0,'sm','smo');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (141,'Sango','yângâ tî sängö',0,'sg','sag');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (142,'Serbian','српски језик',0,'sr','srp');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (143,'Scottish Gaelic; Gaelic','Gàidhlig',0,'gd','gla');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (144,'Shona','chiShona',0,'sn','sna');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (145,'Sinhala, Sinhalese','සිංහල',0,'si','sin');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (146,'Slovak','slovenčina',0,'sk','slk');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (147,'Slovene','slovenščina',0,'sl','slv');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (148,'Somali','Soomaaliga, af Soomaali',0,'so','som');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (149,'Southern Sotho','Sesotho',0,'st','sot');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (150,'Spanish; Castilian','español, castellano',0,'es','spa');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (151,'Sundanese','Basa Sunda',0,'su','sun');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (152,'Swahili','Kiswahili',0,'sw','swa');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (153,'Swati','SiSwati',0,'ss','ssw');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (154,'Swedish','svenska',0,'sv','swe');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (155,'Tamil','தமிழ்',0,'ta','tam');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (156,'Telugu','తెలుగు',0,'te','tel');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (157,'Tajik','тоҷикӣ, toğikī, تاجیکی‎',0,'tg','tgk');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (158,'Thai','ไทย',0,'th','tha');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (159,'Tigrinya','ትግርኛ',0,'ti','tir');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (160,'Tibetan Standard, Tibetan, Central','བོད་ཡིག',0,'bo','bod');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (161,'Turkmen','Türkmen, Түркмен',0,'tk','tuk');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (162,'Tagalog','Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',0,'tl','tgl');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (163,'Tswana','Setswana',0,'tn','tsn');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (164,'Tonga (Tonga Islands)','faka Tonga',0,'to','ton');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (165,'Turkish','Türkçe',0,'tr','tur');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (166,'Tsonga','Xitsonga',0,'ts','tso');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (167,'Tatar','татарча, tatarça, تاتارچا‎',0,'tt','tat');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (168,'Twi','Twi',0,'tw','twi');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (169,'Tahitian','Reo Mā`ohi',0,'ty','tah');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (170,'Uighur, Uyghur','Uyƣurqə, ئۇيغۇرچە‎',0,'ug','uig');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (171,'Ukrainian','Українська',0,'uk','ukr');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (172,'Urdu','اردو',0,'ur','urd');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (173,'Uzbek','O\'zbek, Ўзбек, أۇزبېك‎',0,'uz','uzb');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (174,'Venda','Tshivenḓa',0,'ve','ven');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (175,'Vietnamese','Tiếng Việt',0,'vi','vie');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (176,'Volapük','Volapük',0,'vo','vol');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (177,'Walloon','Walon',0,'wa','wln');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (178,'Welsh','Cymraeg',0,'cy','cym');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (179,'Wolof','Wollof',0,'wo','wol');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (180,'Western Frisian','Frysk',0,'fy','fry');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (181,'Xhosa','isiXhosa',0,'xh','xho');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (182,'Yiddish','ייִדיש',0,'yi','yid');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (183,'Yoruba','Yorùbá',0,'yo','yor');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (184,'Zhuang, Chuang','Saɯ cueŋƅ, Saw cuengh',0,'za','zha');
INSERT INTO `languages` (`id`,`english`,`native`,`enabled`,`iso6391`,`iso6392`) VALUES (185,'Zulu','isiZulu',0,'zu','zul');
